name: Upload Python Package

# This is an adaptation of https://github.com/code-specialist/pypi-poetry-publish.
# That action is released under an MIT License, and as such, so is this workflow.

on:
  workflow_dispatch:
  release:
    types: [created]


env:
  PUBLISH_REGISTRY: https://test.pypi.org/simple

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      Release_Tag: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v4

      - name: testing
        run: echo "$Release_Tag" >> "$GITHUB_OUTPUT"

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Set GitHub Tag as Package Version
        run: |
          sed -i -r 's/__version__ *= *".*"/__version__ = "${{ github.event.release.tag_name }}"/g' ./src/isar/__init__.py
          sed -i '0,/version =.*/s//version = "'"${{ github.event.release.tag_name }}"'"/' ./pyproject.toml
        shell: bash


      - name: Add and Commit Version
        run: |
          git add ./src/isar/__init__.py ./pyproject.toml
          git config --global user.name "PyPI Poetry Publish Bot"
          git config --global user.email "fg_robots_dev@equinor.com"
          git commit -m "Change version to ${{ github.event.release.tag_name }}" --allow-empty
          git push origin HEAD
        shell: bash

      - name: Install dependencies
        run: |
          poetry config virtualenvs.options.no-pip true
          poetry config virtualenvs.options.no-setuptools true
          poetry install --no-root

      - name: Build and Publish
        run: |
          poetry config repositories.publish $PUBLISH_REGISTRY
#          poetry publish -p ${{ secrets.PYPI_TOKEN }} -u __token__ -r publish --build
        shell: bash